services:
  backend:
    image: map-backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - BACKEND_PORT=8080
      - GIN_MODE=release
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s
    networks:
      - history-project-network

  frontend:
    image: map-frontend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      - API_BASE=http://localhost:8080
    restart: unless-stopped
    networks:
      - history-project-network

networks:
  history-project-network:
    driver: bridge

